name: "Test Release versioning"

# on:
#   workflow_call:
#     secrets:
#       initToken:
#         required: true

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  semanticRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.initToken }}
